### PR TITLE
[feature] An attempt at Hayes emulation

### PR DESCRIPTION
**Pull request by Maffsie**
This PR adds Hayes modem emulation, which allows use of the esp_slip_router project on things like Windows 95.
I've managed to successfully use this on my Windows 95 computer (testing was somewhat awkward as it turns out the RS232 transceiver I was using wasn't working).

This PR viewed on IE4/Win95 with this firmware:
IMG_2709

The way it works is that it first boots into "Hayes" command mode, and characters received by the `write_to_pbuf` are redirected to the Hayes emulation code. Once a number is "dialled" (the actual number is ignored, for now), it sets a flag that disables Hayes command mode, putting the router into its normal state (all received characters are passed to the SLIP interface), and the only way to break out of it is to send `+++`.
`ATO` resumes the "call" once back into Hayes command mode, and `ATH` "hangs up". This is purely cosmetic/for accuracy, as I'm not sure how to reset the SLIP interface (or if that's even necessary).

On Windows, configuration is a case of making sure there's a "Standard 28800 baud modem" installed on the appropriate COM port, then adding a new dial-up networking connection. After creating it, go into the settings and change the connection type to SLIP.

### CODE REVIEW

**Comment by martin-ger** [comment]
Thnks for your contribution.

So it is a compile time option: either you start in Heyes mode or a plain serial device?

**Comment by Maffsie** [comment]
It is - the whole thing can be disabled by not defining HAYES_ENABLE.

**Comment by martin-ger** [comment]
Would you mind defining it as default off and documenting it in the readme?
Otherwise the source tree will not compile into the provided binaries and documented behavior.

**Comment by Maffsie** [comment]
No worries - I will default it to disabled.

**Pull request merged**
